### ISSUE TITLE
Next.jsのバージョンを13.3以降にアップグレードしたい

### ISSUE THREAD

**Issue by at946** [at946/tenkir#141]

**Comment by at946** [comment]
https://github.com/vercel/next.js/issues/49334

**Comment by gennei** [comment]
チャレンジしてみようと思ったらそもそもテストが動かなかった。

```sh
$ docker compose run playwright yarn test
[+] Running 1/0
 ⠿ Container tenkir-app-1  Running                                                                                                                                   0.0s
yarn run v1.22.19
$ yarn playwright test
$ /playwright/node_modules/.bin/playwright test


Error: Cannot find module '@/playwright/models/room-page'
Require stack:
- /playwright/tests/rooms/loadingUntilSocketConnected.spec.ts
- /playwright/node_modules/@playwright/test/lib/common/transform.js
- /playwright/node_modules/@playwright/test/lib/common/testType.js
- /playwright/node_modules/@playwright/test/lib/common/test.js
- /playwright/node_modules/@playwright/test/lib/reporters/multiplexer.js
- /playwright/node_modules/@playwright/test/lib/runner/reporters.js
- /playwright/node_modules/@playwright/test/lib/runner/runner.js
- /playwright/node_modules/@playwright/test/lib/cli.js
- /playwright/node_modules/playwright-core/lib/cli/cli.js
- /playwright/node_modules/playwright-core/cli.js
- /playwright/node_modules/playwright/cli.js

   at rooms/loadingUntilSocketConnected.spec.ts:2

  1 | import { expect, test } from '@playwright/test';
> 2 | import RoomPage from '@/playwright/models/room-page';
    | ^
  3 | import createRoomId from '@/playwright/helpers/createRoomId';
  4 |
  5 | test('ルームを参加するとき、WebSocketが確立すると入室完了トーストが表示されること', async ({

    at Object.<anonymous> (/playwright/tests/rooms/loadingUntilSocketConnected.spec.ts:2:1)


To open last HTML report run:

  npx playwright show-report

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by gennei** [comment]
```diff
$ git diff .
diff --git a/playwright/tests/rooms/loadingUntilSocketConnected.spec.ts b/playwright/tests/rooms/loadingUntilSocketConnected.spec.ts
index 44f8f0f..fef286c 100644
--- a/playwright/tests/rooms/loadingUntilSocketConnected.spec.ts
+++ b/playwright/tests/rooms/loadingUntilSocketConnected.spec.ts
@@ -1,6 +1,6 @@
 import { expect, test } from '@playwright/test';
-import RoomPage from '@/playwright/models/room-page';
-import createRoomId from '@/playwright/helpers/createRoomId';
+import RoomPage from '../../../playwright/models/room-page';
+import createRoomId from '../../../playwright/helpers/createRoomId';

 test('ルームを参加するとき、WebSocketが確立すると入室完了トーストが表示されること', async ({
   page,
```

これで動き出した。

**Comment by gennei** [comment]
```sh
$ docker compose run playwright yarn test
[+] Running 1/0
 ⠿ Container tenkir-app-1  Running                                                                                                                                   0.0s
yarn run v1.22.19
$ yarn playwright test
$ /playwright/node_modules/.bin/playwright test

Running 72 tests using 2 workers
····································F···································

  1) [chromium] › rooms/memberLeavesRoom.spec.ts:21:5 › ルームページで、ブラウザを閉じたとき、ルームから抜け出すこと ─────────────

    Error: Timed out 5000ms waiting for expect(received).toHaveCount(expected) // deep equality

    Expected: 1
    Received: 2
    Call log:
      - expect.toHaveCount with timeout 5000ms
      - waiting for getByRole('group', { name: 'テーブルカードグループ' }).getByLabel('テーブルカード')
      -   locator resolved to 2 elements
      -   unexpected value "2"
      -   locator resolved to 2 elements
      -   unexpected value "2"
      -   locator resolved to 2 elements
      -   unexpected value "2"
      -   locator resolved to 2 elements
      -   unexpected value "2"
      -   locator resolved to 2 elements
      -   unexpected value "2"
      -   locator resolved to 2 elements
      -   unexpected value "2"
      -   locator resolved to 2 elements
      -   unexpected value "2"
      -   locator resolved to 2 elements
      -   unexpected value "2"
      -   locator resolved to 2 elements
      -   unexpected value "2"


      34 |
      35 |   // Then
    > 36 |   await expect(roomPage1.tableCards).toHaveCount(1);
         |                                      ^
      37 | });
      38 |

        at /playwright/tests/rooms/memberLeavesRoom.spec.ts:36:38

    attachment #1: video (video/webm) ──────────────────────────────────────────────────────────────
    test-results/rooms-memberLeavesRoom-ルームページで、ブラウザを閉じたとき、ルームから抜け出すこと-chromium/video-1.webm
    ────────────────────────────────────────────────────────────────────────────────────────────────

    attachment #2: video (video/webm) ──────────────────────────────────────────────────────────────
    test-results/rooms-memberLeavesRoom-ルームページで、ブラウザを閉じたとき、ルームから抜け出すこと-chromium/video.webm
    ────────────────────────────────────────────────────────────────────────────────────────────────

    attachment #3: trace (application/zip) ─────────────────────────────────────────────────────────
    test-results/rooms-memberLeavesRoom-ルームページで、ブラウザを閉じたとき、ルームから抜け出すこと-chromium/trace.zip
    Usage:

        npx playwright show-trace test-results/rooms-memberLeavesRoom-ルームページで、ブラウザを閉じたとき、ルームから抜け出すこと-chromium/trace.zip

    ────────────────────────────────────────────────────────────────────────────────────────────────

    attachment #4: screenshot (image/png) ──────────────────────────────────────────────────────────
    test-results/rooms-memberLeavesRoom-ルームページで、ブラウザを閉じたとき、ルームから抜け出すこと-chromium/test-failed-1.png
    ────────────────────────────────────────────────────────────────────────────────────────────────

  1 failed
    [chromium] › rooms/memberLeavesRoom.spec.ts:21:5 › ルームページで、ブラウザを閉じたとき、ルームから抜け出すこと ──────────────
  71 passed (1.7m)

To open last HTML report run:

  npx playwright show-report

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

fail した。

**Comment by gennei** [comment]
とりあえず test 実行ができて issue の通りのエラーが出るところまでできた。ということはもう勝ちだな。
